### ISSUE TITLE
ZUtils.h(25,10): fatal error C1083:

### ISSUE THREAD

**Issue by skylinkdc** [pavel-pimenov/flylinkdc-r6xx#11]
Compilazione avviata...
1>------ Inizio compilazione: Progetto: flylinkdc, Configurazione: Release x64 ------
1>MainFrm.cpp
1>NetworkPage.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\NetworkPage.cpp)
1>QueueFrame.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\MainFrm.cpp)
1>SearchFrm.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\QueueFrame.cpp)
1>StatsFrame.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\SearchFrm.cpp)
1>TransferView.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\TransferView.cpp)
1>WinUtil.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\StatsFrame.cpp)
1>dclstGenDlg.cpp
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\dclstGenDlg.cpp)
1>C:\Users\Lenovo\Desktop\r6xxX64\client\ZUtils.h(25,10): fatal error C1083: Non è possibile aprire il file inclusione: 'zlib-ng.h': No such file or directory (compilazione del file di origine windows\WinUtil.cpp)
1>Compilazione progetto "flylinkdc_2017.vcxproj" NON COMPLETATA.
========== Compilazione: 0 completate, 1 non riuscite, 14 aggiornate, 0 ignorate ==========

**Comment by pavel-pimenov** [comment]
https://github.com/pavel-pimenov/flylinkdc-r6xx/commit/8e27508a831c65779fb07a8585e3939b6d32a9ce ?

**Comment by skylinkdc** [comment]
I recompile the latest version and let you know, if you can make a version with the manual hublist panel (on internet hubs) I would be grateful

**Comment by skylinkdc** [comment]
I downloaded the latest version r6 .. and I was able to compile, the problem is that: if I insert the file to be able to insert the hublists manually, the compilation no longer works, it is possible to make a code to be able to insert the hubs manually like all dc clients ?
