### ISSUE TITLE
Use gpu in tth computation is greyed out

### ISSUE THREAD

**Issue by kotenok2000** [pavel-pimenov/flylinkdc-r6xx#13]
![Снимок экрана (19)](https://user-images.githubusercontent.com/8822292/113822473-252c3c80-9786-11eb-839d-e9581d1e9f6a.png)
At first i thought it was because of an outdated gpu, but when i replaced "amd radeon hd 6570" with "NVIDIA GeForce GTX 1650" it still does not work.

**Comment by pavel-pimenov** [comment]
GPU not implemented
