### ISSUE TITLE
Лишний пробел в меню

### ISSUE THREAD

**Issue by adem4ik** [pavel-pimenov/flylinkdc-r6xx#3]
Версия: r600-x64 build 22434
1) В панели передач нажать правым кликом 
Результат: " IP v4 info XXX.XXX.XXX.XXX" содержит лишний пробел в начале
![FlylinkDC++ r600-x64 build 22434  RAM 96M  138M Free3917M GDI 629  -  •   EuRoPe ShArE NeTwOrK   PrEtOrIAno AnD ChAos HuB ConNeCT • (dchubpretorian](https://user-images.githubusercontent.com/4707112/93707762-650d3880-fb42-11ea-8430-a3e4dd5bbfd7.jpg)

Хотел запуллреквестить фикс с правкой строки https://github.com/pavel-pimenov/flylinkdc-r6xx/blob/master/windows/WinUtil.cpp#L4098 , но столкнулся с другой проблемой https://github.com/pavel-pimenov/flylinkdc-r6xx/issues/2

**Comment by pavel-pimenov** [comment]
https://github.com/pavel-pimenov/flylinkdc-r6xx/commit/70e2de5f6f582f61654c285f702df0686d55544f

**Comment by adem4ik** [comment]
@pavel-pimenov Спасибо! Но мне кажется, правка вот этих строк не требовалась, там как раз-таки нужен пробел после "Whois" (см. скрин в заглавном посте):
![image](https://user-images.githubusercontent.com/4707112/94689043-6ce98b80-033f-11eb-8140-4754504e803a.png)
