### ISSUE TITLE
major error on adc:// and adcs://   hubs

### ISSUE THREAD

**Issue by skylinkdc** [pavel-pimenov/flylinkdc-r6xx#31]
I compiled the latest version of FlylinkDC ++, entering the adc and adcs hubs on the right of the client you no longer see the Nick - Share - Description - Version - etc etc

**Comment by skylinkdc** [comment]
there is always the same problem, on the adc adcs hubs you don't see the NICK List Share - Description - Version - etc etc

**Comment by Tantrix** [comment]
Исправлено в билде 22916.
