### ISSUE TITLE
hub adcs

### ISSUE THREAD

**Issue by skylinkdc** [pavel-pimenov/flylinkdc-r6xx#32]
![flylinkdc](https://user-images.githubusercontent.com/41260139/152636568-29045bcd-6468-4216-9e74-b43b410232e2.png)

there is always the same problem, on the adc adcs hubs you don't see the NICK List Share - Description - Version - etc etc

**Comment by pavel-pimenov** [comment]
url?

**Comment by skylinkdc** [comment]
adcs://uhub.dchub.in.ua:511                  are all adcs hubs with this problem, not just 1 url, but all of them

**Comment by Tantrix** [comment]
Подтверждаю. Такое на всех ADC хабах.

**Comment by Tantrix** [comment]
Исправлено в билде 22916.
