### ISSUE TITLE
Antispam Url

### ISSUE THREAD

**Issue by skylinkdc** [pavel-pimenov/flylinkdc-r6xx#7]
hello
http://etc.fly-server.ru/etc/flylinkdc-config-r5xx.xml
http://etc.fly-server.ru/etc/flylinkdc-config-r6xx.xml

Delete my domain , please

**Comment by pavel-pimenov** [comment]
dchublist.biz ?

**Comment by skylinkdc** [comment]
yes

**Comment by pavel-pimenov** [comment]
remove
